-- 코드를 입력하세요
WITH MILK_CART AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
),

YOGURT_CART AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)

SELECT DISTINCT CART_ID

FROM CART_PRODUCTS

WHERE 
    CART_ID IN(SELECT * FROM MILK_CART) AND
    CART_ID IN(SELECT * FROM YOGURT_CART)
    
ORDER BY CART_ID ASC;