-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.NAME

FROM ANIMAL_INS I 

-- 그냥 JOIN하면 어차피 OUT에 없는 동물은 안뜸!
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID

ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC

LIMIT 2;

