WITH TARGET AS (
    SELECT
        REST_ID,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK  
    FROM    
        REST_INFO
)
SELECT 
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM
    REST_INFO
WHERE
    REST_ID IN (SELECT REST_ID FROM TARGET WHERE RNK = 1)
ORDER BY
    FOOD_TYPE DESC;
