-- 코드를 입력하세요
WITH POSTED_OVER_3_USER AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)

SELECT 
    DISTINCT U.USER_ID, 
    U.NICKNAME, 
    CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소',
    CONCAT_WS('-', SUBSTR(U.TLNO, 1, 3), SUBSTR(U.TLNO, 4, 4), SUBSTR(U.TLNO, 8, 4)) AS '전화번호'
     
FROM USED_GOODS_USER U

JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID

WHERE U.USER_ID IN (SELECT * FROM POSTED_OVER_3_USER)

ORDER BY U.USER_ID DESC;
