WITH RECURSIVE GENERATION AS (
    SELECT
        ID,
        1 AS GEN
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    UNION ALL
    SELECT
        E.ID,
        GEN + 1
    FROM 
        GENERATION G
    JOIN
        ECOLI_DATA E
        ON G.ID = E.PARENT_ID
)
SELECT
    COUNT(E.ID) AS COUNT,
    G.GEN AS GENERATION
FROM
    ECOLI_DATA E
JOIN
    GENERATION G
    ON E.ID = G.ID
WHERE
    E.ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY
    GENERATION
ORDER BY
    GENERATION ASC;
