-- 해당 날짜에 하나라도 대여 중인 자동차를 미리 골라 놓기
WITH TARGET AS (
    SELECT DISTINCT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        '2022-10-16' BETWEEN START_DATE AND END_DATE
)
SELECT DISTINCT
    CAR_ID,
    (
        CASE
            WHEN EXISTS (SELECT * FROM TARGET I WHERE O.CAR_ID = I.CAR_ID) THEN '대여중'
            ELSE '대여 가능'
        END
    ) AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY O
ORDER BY 
    CAR_ID DESC;