-- 코드를 입력하세요
WITH OLDEST_3 AS(
    SELECT I.ANIMAL_ID
    
    FROM ANIMAL_INS I
    
    LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    
    WHERE O.ANIMAL_ID IS NULL
    
    ORDER BY I.DATETIME ASC
    
    LIMIT 3
)

SELECT I.NAME, I.DATETIME

FROM ANIMAL_INS I

LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID

WHERE O.ANIMAL_ID IS NULL AND I.ANIMAL_ID IN (SELECT * FROM OLDEST_3)

ORDER BY I.DATETIME ASC;