-- 코드를 입력하세요
SELECT 
    HISTORY_ID, 
    FLOOR((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * R.DAILY_FEE * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100) AS FEE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H

JOIN CAR_RENTAL_COMPANY_CAR R
    ON H.CAR_ID = R.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON R.CAR_TYPE = D.CAR_TYPE AND
    D.DURATION_TYPE =   (
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END
    )
    
    
    
WHERE 
    R.CAR_TYPE = '트럭'
    
ORDER BY FEE DESC, HISTORY_ID DESC;
    

