WITH HISTORY_INFO AS (
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        (
            CASE
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE NULL
            END
        ) DURATION_TYPE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    
    JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    
    WHERE C.CAR_TYPE = '트럭'
)

SELECT
    I.HISTORY_ID,
    (
        TRUNCATE(I.DAILY_FEE * DURATION * ((100 - IFNULL(DISCOUNT_RATE, 0)) / 100), 0)
        
    ) AS FEE
        
        
FROM HISTORY_INFO I

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON I.DURATION_TYPE = D.DURATION_TYPE
        AND D.CAR_TYPE = '트럭'

ORDER BY FEE DESC, I.HISTORY_ID DESC;