WITH TARGET AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(CAR_ID) >= 5
)

SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(CAR_ID) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY O
WHERE
    EXISTS (
        SELECT * FROM TARGET I WHERE O.CAR_ID = I.CAR_ID
    ) AND
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH,
    CAR_ID
HAVING
    RECORDS > 0
ORDER BY
    MONTH ASC,
    CAR_ID DESC;