-- 코드를 작성해주세요
WITH LONGEST AS (
    
    SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS MAXIMUM
    
    FROM ECOLI_DATA
    
    GROUP BY YEAR

)

SELECT 
    L.YEAR,
    (L.MAXIMUM - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
    
FROM ECOLI_DATA E
    
JOIN LONGEST L ON YEAR(E.DIFFERENTIATION_DATE) = L.YEAR
    
ORDER BY L.YEAR ASC, YEAR_DEV ASC;