SELECT ID, FISH_NAME, LENGTH

FROM (
    
    SELECT 
        F.ID, 
        N.FISH_NAME,
        F.LENGTH,
        RANK() OVER (PARTITION BY F.FISH_TYPE ORDER BY F.LENGTH DESC) AS RK
    
    FROM FISH_INFO F
    
    JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE

) AS TMP

WHERE RK = 1

ORDER BY ID ASC;