WITH TARGET AS (
    SELECT 
        *,
        RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO
)

SELECT
    T.ID,
    I.FISH_NAME,
    T.LENGTH
FROM
    TARGET T
JOIN
    FISH_NAME_INFO I
    ON T.FISH_TYPE = I.FISH_TYPE
    
WHERE
    RNK = 1
ORDER BY 
    ID ASC;