WITH TMP AS(
    
    SELECT FISH_TYPE, MAX(LENGTH) AS 'LENGTH'
    
    FROM FISH_INFO
    
    GROUP BY FISH_TYPE
)

SELECT I.ID, N.FISH_NAME, I.LENGTH

FROM FISH_INFO I

JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE

WHERE (N.FISH_TYPE, I.LENGTH) IN (SELECT FISH_TYPE, LENGTH FROM TMP)

ORDER BY ID ASC;