-- 코드를 입력하세요
WITH MOST_VIEW_BOARD AS (
    SELECT BOARD_ID
    
    FROM USED_GOODS_BOARD
    
    ORDER BY VIEWS DESC
    
    LIMIT 1
)
SELECT 
    CONCAT(
        '/home/grep/src/',
        F.BOARD_ID,
        '/',
        F.FILE_ID,
        F.FILE_NAME,
        F.FILE_EXT
    ) AS FILE_PATH
FROM USED_GOODS_FILE F

JOIN USED_GOODS_BOARD B ON F.BOARD_ID = B.BOARD_ID

WHERE B.BOARD_ID = (SELECT * FROM MOST_VIEW_BOARD)

ORDER BY F.FILE_ID DESC;